#!/usr/bin/env python3
"""
NEXUS Local Wake Word Trainer & Optimizer
Extracts ONNX embeddings from real laptop recordings and trains a custom 128-dim KWS classifier.
"""

import os
import sys
import glob
from pathlib import Path
import numpy as np

# Fix Windows console encoding
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import onnxruntime as ort
from scipy.io import wavfile

ROOT = Path(__file__).resolve().parent.parent
OWW_DIR = ROOT / "src-tauri" / "resources" / "oww"
# reads your real recordings + all synth_*.wav clips generated by augment_vocabulary.py
DATA_DIR = ROOT / "wake_word_data"

CHUNK = 1280
LOOKBACK = 480
MEL_PER_CHUNK = 8
MEL_CIRC = 10
EMB_FRAMES = 16
TARGET_RMS = 0.03
MAX_GAIN = 15.0
SILENCE_RMS = 0.002


class OwwClassifier(nn.Module):
    def __init__(self, input_dim=16*96, hidden_dim=128):
        super().__init__()
        self.layer1 = nn.Linear(input_dim, hidden_dim)
        self.layernorm1 = nn.LayerNorm(hidden_dim)
        self.relu1 = nn.ReLU()
        
        self.layer2 = nn.Linear(hidden_dim, hidden_dim)
        self.layernorm2 = nn.LayerNorm(hidden_dim)
        self.relu2 = nn.ReLU()
        
        self.last_layer = nn.Linear(hidden_dim, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # x shape: [batch, 16, 96]
        batch_size = x.shape[0]
        view = x.view(batch_size, -1)
        
        linear = self.layer1(view)
        norm1 = self.layernorm1(linear)
        relu = self.relu1(norm1)
        
        linear_1 = self.layer2(relu)
        norm2 = self.layernorm2(linear_1)
        relu_1 = self.relu2(norm2)
        
        linear_2 = self.last_layer(relu_1)
        return self.sigmoid(linear_2)


def extract_clip_embeddings(wav_path, mel_sess, emb_sess, names, is_positive=False):
    """Extract all valid 16-frame embedding windows from a WAV file."""
    sr, data = wavfile.read(wav_path)
    if sr != 16000:
        return []
    if data.ndim > 1:
        data = data.mean(axis=1)
    audio = data.astype(np.float32) / 32768.0

    # Highpass filter (80Hz)
    dt = 1.0 / 16000.0
    rc = 1.0 / (2.0 * np.pi * 80.0)
    alpha = rc / (rc + dt)
    filtered = np.empty_like(audio)
    prev_y = 0.0
    prev_x = 0.0
    for i in range(len(audio)):
        y = alpha * (prev_y + audio[i] - prev_x)
        prev_x = audio[i]
        prev_y = y
        filtered[i] = y
    audio = filtered

    lookback = np.zeros(LOOKBACK, dtype=np.float32)
    mel_buf = [np.zeros((MEL_PER_CHUNK, 32), dtype=np.float32)] * MEL_CIRC
    emb_buf = [np.zeros(96, dtype=np.float32)] * EMB_FRAMES
    
    windows = []
    
    for i in range(0, len(audio) - CHUNK + 1, CHUNK):
        chunk = audio[i:i + CHUNK].copy()
        rms = float(np.sqrt(np.mean(chunk ** 2)))
        
        if rms < SILENCE_RMS:
            continue
            
        if rms < TARGET_RMS:
            gain = min(TARGET_RMS / rms, MAX_GAIN)
            chunk = np.clip(chunk * gain, -1.0, 1.0)
            
        framed = np.concatenate([lookback, chunk]) * 32768.0
        lookback = chunk[-LOOKBACK:]
        
        m = mel_sess.run(None, {names[0]: framed[None, :]})[0]
        m = m.reshape(MEL_PER_CHUNK, 32) / 10.0 + 2.0
        mel_buf = (mel_buf + [m])[-MEL_CIRC:]
        
        window = np.stack(mel_buf).reshape(80, 32)[4:80]
        e = emb_sess.run(None, {names[1]: window[None, :, :, None].astype(np.float32)})[0]
        emb_buf = (emb_buf + [e.reshape(-1)])[-EMB_FRAMES:]
        
        # Collect full 16-frame embedding context
        stacked = np.stack(emb_buf).astype(np.float32)
        windows.append(stacked)
        
    return windows


def main():
    print("=" * 60)
    print("  NEXUS REAL ACOUSTIC WAKE WORD TRAINING")
    print("=" * 60)
    
    mel = ort.InferenceSession(str(OWW_DIR / 'melspectrogram.onnx'))
    emb = ort.InferenceSession(str(OWW_DIR / 'embedding_model.onnx'))
    names = (mel.get_inputs()[0].name, emb.get_inputs()[0].name)
    
    X_pos = []
    X_neg = []
    
    print("\n1. Extracting features from POSITIVE recordings...")
    pos_files = sorted(glob.glob(str(DATA_DIR / "positive" / "*.wav")))
    for p in pos_files:
        wins = extract_clip_embeddings(p, mel, emb, names, is_positive=True)
        if wins:
            # The peak embedding window contains the trigger
            X_pos.extend(wins[-3:]) # Last 3 windows contain the completed wake word
    print(f"   Collected {len(X_pos)} positive training windows from {len(pos_files)} clips.")

    print("\n2. Extracting features from NEGATIVE soundalike recordings...")
    neg_files = sorted(glob.glob(str(DATA_DIR / "negative" / "*.wav")))
    for p in neg_files:
        wins = extract_clip_embeddings(p, mel, emb, names, is_positive=False)
        if wins:
            X_neg.extend(wins)
    print(f"   Collected {len(X_neg)} negative soundalike windows from {len(neg_files)} clips.")

    print("\n3. Extracting features from BACKGROUND noise recordings...")
    bg_files = sorted(glob.glob(str(DATA_DIR / "background" / "*.wav")))
    for p in bg_files:
        wins = extract_clip_embeddings(p, mel, emb, names, is_positive=False)
        if wins:
            X_neg.extend(wins)
    print(f"   Total negative windows (Soundalikes + Noise): {len(X_neg)}")

    X_pos = np.array(X_pos, dtype=np.float32)
    y_pos = np.ones((len(X_pos), 1), dtype=np.float32)
    
    X_neg = np.array(X_neg, dtype=np.float32)
    y_neg = np.zeros((len(X_neg), 1), dtype=np.float32)
    
    # Shuffle and split into Train & Validation (80/20)
    np.random.seed(42)
    torch.manual_seed(42)
    
    idx_pos = np.random.permutation(len(X_pos))
    split_pos = int(0.8 * len(X_pos))
    X_pos_train, X_pos_val = X_pos[idx_pos[:split_pos]], X_pos[idx_pos[split_pos:]]
    y_pos_train, y_pos_val = y_pos[idx_pos[:split_pos]], y_pos[idx_pos[split_pos:]]
    
    idx_neg = np.random.permutation(len(X_neg))
    split_neg = int(0.8 * len(X_neg))
    X_neg_train, X_neg_val = X_neg[idx_neg[:split_neg]], X_neg[idx_neg[split_neg:]]
    y_neg_train, y_neg_val = y_neg[idx_neg[:split_neg]], y_neg[idx_neg[split_neg:]]
    
    X_train = np.concatenate([X_pos_train, X_neg_train], axis=0)
    y_train = np.concatenate([y_pos_train, y_neg_train], axis=0)
    
    X_val = np.concatenate([X_pos_val, X_neg_val], axis=0)
    y_val = np.concatenate([y_pos_val, y_neg_val], axis=0)
    
    train_dataset = TensorDataset(torch.from_numpy(X_train), torch.from_numpy(y_train))
    train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
    
    print(f"\nTraining Dataset: {len(X_train)} samples ({len(X_pos_train)} pos, {len(X_neg_train)} neg)")
    print(f"Validation Dataset: {len(X_val)} samples ({len(X_pos_val)} pos, {len(X_neg_val)} neg)")
    
    # Initialize Model & Loss
    model = OwwClassifier()
    # Heavy negative class weight: forces the model to STRONGLY reject non-NEXUS speech.
    # With 8x more negatives, the model learns to be conservative — only fire on NEXUS.
    pos_weight = torch.tensor([8.0])
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    optimizer = optim.AdamW(model.parameters(), lr=0.001, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=60)
    
    # Wrap model to add sigmoid for ONNX export (BCEWithLogitsLoss works on logits internally)
    class SigmoidWrapper(nn.Module):
        def __init__(self, base):
            super().__init__()
            self.base = base
        def forward(self, x):
            return torch.sigmoid(self.base(x))
    
    # Patch last layer to output logits (remove sigmoid from classifier for BCEWithLogitsLoss)
    model.sigmoid = nn.Identity()

    print("\n4. Training Neural Classifier...")
    best_val_loss = float('inf')
    best_weights = None
    THRESHOLD = 0.50  # Stricter threshold — must be clearly NEXUS to trigger
    
    for epoch in range(1, 61):
        model.train()
        total_loss = 0.0
        for bx, by in train_loader:
            optimizer.zero_grad()
            preds = model(bx)
            loss = criterion(preds, by)
            loss.backward()
            optimizer.step()
            total_loss += loss.item() * len(bx)
        scheduler.step()
        
        # Validation
        model.eval()
        with torch.no_grad():
            val_preds = model(torch.from_numpy(X_val)).numpy()
            val_loss = criterion(torch.from_numpy(val_preds), torch.from_numpy(y_val)).item()
            
            # Compute recall and rejection rate @ THRESHOLD
            pos_preds = torch.sigmoid(torch.from_numpy(val_preds)).numpy()
            neg_preds = torch.sigmoid(torch.from_numpy(val_preds)).numpy()
            
            all_sigmoid = torch.sigmoid(torch.from_numpy(val_preds)).numpy()
            pos_sigmoid = all_sigmoid[:len(X_pos_val)]
            neg_sigmoid = all_sigmoid[len(X_pos_val):]
            
            recall = np.mean(pos_sigmoid >= THRESHOLD)
            fa_rate = np.mean(neg_sigmoid >= THRESHOLD)
            
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_weights = model.state_dict().copy()
                
            if epoch % 5 == 0 or epoch == 1:
                print(f"   Epoch {epoch:2d}/60 — Loss: {total_loss/len(X_train):.4f} | Val Loss: {val_loss:.4f} | Recall: {recall:6.1%} | False Alarm: {fa_rate:6.1%}")

    print("\n5. Restoring best model & exporting to ONNX...")
    model.load_state_dict(best_weights)
    model.eval()
    
    # Wrap with sigmoid for ONNX (BCEWithLogitsLoss trains on raw logits, but ONNX must output 0-1)
    export_model = SigmoidWrapper(model)
    export_model.eval()
    
    # Export to ONNX matching openWakeWord exact naming and input shape [1, 16, 96]
    dummy_input = torch.randn(1, 16, 96, dtype=torch.float32)
    output_onnx = str(ROOT / "src-tauri" / "resources" / "oww" / "nexus.onnx")
    
    # Backup previous model
    backup_onnx = str(ROOT / "src-tauri" / "resources" / "oww" / "nexus.onnx.bak")
    if os.path.exists(output_onnx):
        import shutil
        shutil.copy2(output_onnx, backup_onnx)
        
    torch.onnx.export(
        export_model,
        dummy_input,
        output_onnx,
        input_names=["x"],
        output_names=["sigmoid"],
        dynamic_axes={"x": {0: "batch_size"}, "sigmoid": {0: "batch_size"}},
        opset_version=14,
        dynamo=False,
    )
    
    print(f"   Saved optimized ONNX model to: {output_onnx}")
    print("=" * 60)
    print("  TRAINING COMPLETE! READY FOR VERIFICATION")
    print("=" * 60)


if __name__ == "__main__":
    main()
